/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AnalyticsCrewRouteImport } from './routes/analytics.crew'
import { Route as AnalyticsFleetRouteImport } from './routes/analytics.fleet'
import { Route as AnalyticsIncidentsRouteImport } from './routes/analytics.incidents'
import { Route as AnalyticsPlanVsActualRouteImport } from './routes/analytics.plan-vs-actual'
import { Route as AnalyticsRoutesRouteImport } from './routes/analytics.routes'
import { Route as CrewAvailabilityRouteImport } from './routes/crew.availability'
import { Route as CrewConductorsRouteImport } from './routes/crew.conductors'
import { Route as CrewDriversRouteImport } from './routes/crew.drivers'
import { Route as FleetBusesRouteImport } from './routes/fleet.buses'
import { Route as FleetMaintenanceRouteImport } from './routes/fleet.maintenance'
import { Route as NetworkPlannerRouteImport } from './routes/network.planner'
import { Route as NetworkRoutesRouteImport } from './routes/network.routes'
import { Route as OperationsDutiesRouteImport } from './routes/operations.duties'
import { Route as OperationsIncidentsRouteImport } from './routes/operations.incidents'
import { Route as OperationsTodayRouteImport } from './routes/operations.today'
import { Route as OperationsTripsRouteImport } from './routes/operations.trips'
import { Route as SchedulingOptimizerRouteImport } from './routes/scheduling.optimizer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsCrewRoute = AnalyticsCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsFleetRoute = AnalyticsFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsIncidentsRoute = AnalyticsIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsPlanVsActualRoute = AnalyticsPlanVsActualRouteImport.update({
  id: '/plan-vs-actual',
  path: '/plan-vs-actual',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsRoutesRoute = AnalyticsRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AnalyticsRoute,
} as any)
const CrewAvailabilityRoute = CrewAvailabilityRouteImport.update({
  id: '/crew/availability',
  path: '/crew/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewConductorsRoute = CrewConductorsRouteImport.update({
  id: '/crew/conductors',
  path: '/crew/conductors',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewDriversRoute = CrewDriversRouteImport.update({
  id: '/crew/drivers',
  path: '/crew/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetBusesRoute = FleetBusesRouteImport.update({
  id: '/fleet/buses',
  path: '/fleet/buses',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetMaintenanceRoute = FleetMaintenanceRouteImport.update({
  id: '/fleet/maintenance',
  path: '/fleet/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkPlannerRoute = NetworkPlannerRouteImport.update({
  id: '/network/planner',
  path: '/network/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoutesRoute = NetworkRoutesRouteImport.update({
  id: '/network/routes',
  path: '/network/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsDutiesRoute = OperationsDutiesRouteImport.update({
  id: '/operations/duties',
  path: '/operations/duties',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIncidentsRoute = OperationsIncidentsRouteImport.update({
  id: '/operations/incidents',
  path: '/operations/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsTodayRoute = OperationsTodayRouteImport.update({
  id: '/operations/today',
  path: '/operations/today',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsTripsRoute = OperationsTripsRouteImport.update({
  id: '/operations/trips',
  path: '/operations/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingOptimizerRoute = SchedulingOptimizerRouteImport.update({
  id: '/scheduling/optimizer',
  path: '/scheduling/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/analytics/crew': typeof AnalyticsCrewRoute
  '/analytics/fleet': typeof AnalyticsFleetRoute
  '/analytics/incidents': typeof AnalyticsIncidentsRoute
  '/analytics/plan-vs-actual': typeof AnalyticsPlanVsActualRoute
  '/analytics/routes': typeof AnalyticsRoutesRoute
  '/crew/availability': typeof CrewAvailabilityRoute
  '/crew/conductors': typeof CrewConductorsRoute
  '/crew/drivers': typeof CrewDriversRoute
  '/fleet/buses': typeof FleetBusesRoute
  '/fleet/maintenance': typeof FleetMaintenanceRoute
  '/network/planner': typeof NetworkPlannerRoute
  '/network/routes': typeof NetworkRoutesRoute
  '/operations/duties': typeof OperationsDutiesRoute
  '/operations/incidents': typeof OperationsIncidentsRoute
  '/operations/today': typeof OperationsTodayRoute
  '/operations/trips': typeof OperationsTripsRoute
  '/scheduling/optimizer': typeof SchedulingOptimizerRoute
  '/analytics/': typeof AnalyticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/analytics/crew': typeof AnalyticsCrewRoute
  '/analytics/fleet': typeof AnalyticsFleetRoute
  '/analytics/incidents': typeof AnalyticsIncidentsRoute
  '/analytics/plan-vs-actual': typeof AnalyticsPlanVsActualRoute
  '/analytics/routes': typeof AnalyticsRoutesRoute
  '/crew/availability': typeof CrewAvailabilityRoute
  '/crew/conductors': typeof CrewConductorsRoute
  '/crew/drivers': typeof CrewDriversRoute
  '/fleet/buses': typeof FleetBusesRoute
  '/fleet/maintenance': typeof FleetMaintenanceRoute
  '/network/planner': typeof NetworkPlannerRoute
  '/network/routes': typeof NetworkRoutesRoute
  '/operations/duties': typeof OperationsDutiesRoute
  '/operations/incidents': typeof OperationsIncidentsRoute
  '/operations/today': typeof OperationsTodayRoute
  '/operations/trips': typeof OperationsTripsRoute
  '/scheduling/optimizer': typeof SchedulingOptimizerRoute
  '/analytics': typeof AnalyticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/analytics/crew': typeof AnalyticsCrewRoute
  '/analytics/fleet': typeof AnalyticsFleetRoute
  '/analytics/incidents': typeof AnalyticsIncidentsRoute
  '/analytics/plan-vs-actual': typeof AnalyticsPlanVsActualRoute
  '/analytics/routes': typeof AnalyticsRoutesRoute
  '/crew/availability': typeof CrewAvailabilityRoute
  '/crew/conductors': typeof CrewConductorsRoute
  '/crew/drivers': typeof CrewDriversRoute
  '/fleet/buses': typeof FleetBusesRoute
  '/fleet/maintenance': typeof FleetMaintenanceRoute
  '/network/planner': typeof NetworkPlannerRoute
  '/network/routes': typeof NetworkRoutesRoute
  '/operations/duties': typeof OperationsDutiesRoute
  '/operations/incidents': typeof OperationsIncidentsRoute
  '/operations/today': typeof OperationsTodayRoute
  '/operations/trips': typeof OperationsTripsRoute
  '/scheduling/optimizer': typeof SchedulingOptimizerRoute
  '/analytics/': typeof AnalyticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/settings'
    | '/simulation'
    | '/analytics/crew'
    | '/analytics/fleet'
    | '/analytics/incidents'
    | '/analytics/plan-vs-actual'
    | '/analytics/routes'
    | '/crew/availability'
    | '/crew/conductors'
    | '/crew/drivers'
    | '/fleet/buses'
    | '/fleet/maintenance'
    | '/network/planner'
    | '/network/routes'
    | '/operations/duties'
    | '/operations/incidents'
    | '/operations/today'
    | '/operations/trips'
    | '/scheduling/optimizer'
    | '/analytics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/simulation'
    | '/analytics/crew'
    | '/analytics/fleet'
    | '/analytics/incidents'
    | '/analytics/plan-vs-actual'
    | '/analytics/routes'
    | '/crew/availability'
    | '/crew/conductors'
    | '/crew/drivers'
    | '/fleet/buses'
    | '/fleet/maintenance'
    | '/network/planner'
    | '/network/routes'
    | '/operations/duties'
    | '/operations/incidents'
    | '/operations/today'
    | '/operations/trips'
    | '/scheduling/optimizer'
    | '/analytics'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/settings'
    | '/simulation'
    | '/analytics/crew'
    | '/analytics/fleet'
    | '/analytics/incidents'
    | '/analytics/plan-vs-actual'
    | '/analytics/routes'
    | '/crew/availability'
    | '/crew/conductors'
    | '/crew/drivers'
    | '/fleet/buses'
    | '/fleet/maintenance'
    | '/network/planner'
    | '/network/routes'
    | '/operations/duties'
    | '/operations/incidents'
    | '/operations/today'
    | '/operations/trips'
    | '/scheduling/optimizer'
    | '/analytics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SimulationRoute: typeof SimulationRoute
  CrewAvailabilityRoute: typeof CrewAvailabilityRoute
  CrewConductorsRoute: typeof CrewConductorsRoute
  CrewDriversRoute: typeof CrewDriversRoute
  FleetBusesRoute: typeof FleetBusesRoute
  FleetMaintenanceRoute: typeof FleetMaintenanceRoute
  NetworkPlannerRoute: typeof NetworkPlannerRoute
  NetworkRoutesRoute: typeof NetworkRoutesRoute
  OperationsDutiesRoute: typeof OperationsDutiesRoute
  OperationsIncidentsRoute: typeof OperationsIncidentsRoute
  OperationsTodayRoute: typeof OperationsTodayRoute
  OperationsTripsRoute: typeof OperationsTripsRoute
  SchedulingOptimizerRoute: typeof SchedulingOptimizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/crew': {
      id: '/analytics/crew'
      path: '/crew'
      fullPath: '/analytics/crew'
      preLoaderRoute: typeof AnalyticsCrewRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/fleet': {
      id: '/analytics/fleet'
      path: '/fleet'
      fullPath: '/analytics/fleet'
      preLoaderRoute: typeof AnalyticsFleetRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/incidents': {
      id: '/analytics/incidents'
      path: '/incidents'
      fullPath: '/analytics/incidents'
      preLoaderRoute: typeof AnalyticsIncidentsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/plan-vs-actual': {
      id: '/analytics/plan-vs-actual'
      path: '/plan-vs-actual'
      fullPath: '/analytics/plan-vs-actual'
      preLoaderRoute: typeof AnalyticsPlanVsActualRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/routes': {
      id: '/analytics/routes'
      path: '/routes'
      fullPath: '/analytics/routes'
      preLoaderRoute: typeof AnalyticsRoutesRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/crew/availability': {
      id: '/crew/availability'
      path: '/crew/availability'
      fullPath: '/crew/availability'
      preLoaderRoute: typeof CrewAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/conductors': {
      id: '/crew/conductors'
      path: '/crew/conductors'
      fullPath: '/crew/conductors'
      preLoaderRoute: typeof CrewConductorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/drivers': {
      id: '/crew/drivers'
      path: '/crew/drivers'
      fullPath: '/crew/drivers'
      preLoaderRoute: typeof CrewDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/buses': {
      id: '/fleet/buses'
      path: '/fleet/buses'
      fullPath: '/fleet/buses'
      preLoaderRoute: typeof FleetBusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/maintenance': {
      id: '/fleet/maintenance'
      path: '/fleet/maintenance'
      fullPath: '/fleet/maintenance'
      preLoaderRoute: typeof FleetMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/planner': {
      id: '/network/planner'
      path: '/network/planner'
      fullPath: '/network/planner'
      preLoaderRoute: typeof NetworkPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/routes': {
      id: '/network/routes'
      path: '/network/routes'
      fullPath: '/network/routes'
      preLoaderRoute: typeof NetworkRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/duties': {
      id: '/operations/duties'
      path: '/operations/duties'
      fullPath: '/operations/duties'
      preLoaderRoute: typeof OperationsDutiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/incidents': {
      id: '/operations/incidents'
      path: '/operations/incidents'
      fullPath: '/operations/incidents'
      preLoaderRoute: typeof OperationsIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/today': {
      id: '/operations/today'
      path: '/operations/today'
      fullPath: '/operations/today'
      preLoaderRoute: typeof OperationsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/trips': {
      id: '/operations/trips'
      path: '/operations/trips'
      fullPath: '/operations/trips'
      preLoaderRoute: typeof OperationsTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/optimizer': {
      id: '/scheduling/optimizer'
      path: '/scheduling/optimizer'
      fullPath: '/scheduling/optimizer'
      preLoaderRoute: typeof SchedulingOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsCrewRoute: typeof AnalyticsCrewRoute
  AnalyticsFleetRoute: typeof AnalyticsFleetRoute
  AnalyticsIncidentsRoute: typeof AnalyticsIncidentsRoute
  AnalyticsPlanVsActualRoute: typeof AnalyticsPlanVsActualRoute
  AnalyticsRoutesRoute: typeof AnalyticsRoutesRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsCrewRoute: AnalyticsCrewRoute,
  AnalyticsFleetRoute: AnalyticsFleetRoute,
  AnalyticsIncidentsRoute: AnalyticsIncidentsRoute,
  AnalyticsPlanVsActualRoute: AnalyticsPlanVsActualRoute,
  AnalyticsRoutesRoute: AnalyticsRoutesRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SimulationRoute: SimulationRoute,
  CrewAvailabilityRoute: CrewAvailabilityRoute,
  CrewConductorsRoute: CrewConductorsRoute,
  CrewDriversRoute: CrewDriversRoute,
  FleetBusesRoute: FleetBusesRoute,
  FleetMaintenanceRoute: FleetMaintenanceRoute,
  NetworkPlannerRoute: NetworkPlannerRoute,
  NetworkRoutesRoute: NetworkRoutesRoute,
  OperationsDutiesRoute: OperationsDutiesRoute,
  OperationsIncidentsRoute: OperationsIncidentsRoute,
  OperationsTodayRoute: OperationsTodayRoute,
  OperationsTripsRoute: OperationsTripsRoute,
  SchedulingOptimizerRoute: SchedulingOptimizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
